POUND INCLUDE LANGLE STANDARD INPUT OUTPUT DOT HEADER FILE RANGLE SEMICOLON

INT MAIN LPAREN RPAREN LBRACE
SPACE SPACE SPACE SPACE STANDARD MODULE SEPARATOR CHARACTER OUTPUT LSHIFT QUOTE My name is Alvin S of C END QUOTE LSHIFT STANDARD MODULE SEPARATOR END LINE SEMICOLON
RETURN 0 SEMICOLON
RBRACE
